package com.example.autoclicker

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object Lang {
    var current by mutableStateOf("tr")
        private set

    private val all = mapOf(
        "tr" to mapOf(
            "home" to "Ana Sayfa",
            "help" to "Yardım",
            "feedback" to "Geri Bildirim",
            "about" to "Uygulama Hakkında",
            "exit" to "Çıkış",
            "app_name" to "Auto Clicker",
            "app_subtitle" to "Otomatik Tıklama Aracı",
            "a11y_title" to "Erişilebilirlik Servisi Gerekli",
            "a11y_text" to "Auto Clicker'ın çalışması için erişilebilirlik servisini açmanız gerekiyor:\nAyarlar > Erişilebilirlik > Auto Clicker",
            "a11y_go" to "Ayarlara Git",
            "a11y_later" to "Daha Sonra",
            "mode_title" to "Çalışma Modu",
            "mode_single" to "Tek Hedef",
            "mode_multi" to "Çoklu Hedef",
            "panel_title" to "Yüzen Panel",
            "panel_active" to "Aktif — tüm ayarlar panelden yapılır",
            "panel_off" to "Kapalı",
            "panel_hint" to "Tüm ayarlar yüzen paneldeki ⚙ butonundan yapılır",
            "badge_service" to "Servis",
            "badge_enable" to "Aç",
            "badge_overlay" to "Overlay",
            "badge_grant" to "İzin Ver",
            "help_title" to "Yardım",
            "help_setup" to "Kurulum",
            "help_step1" to "Erişilebilirlik Servisini Açın",
            "help_step1_desc" to "Ayarlar > Erişilebilirlik > Auto Clicker yolundan servisi etkinleştirin.",
            "help_step2" to "Overlay İzni Verin",
            "help_step2_desc" to "Yüzen panel için ekran üstünde görüntüleme iznini kabul edin.",
            "help_step3" to "Yüzen Paneli Açın",
            "help_step3_desc" to "Ana ekrandaki switch ile yüzen paneli aktif hale getirin.",
            "help_usage" to "Kullanım",
            "help_single" to "Tek Hedef",
            "help_single_desc" to "Tek bir noktaya belirlediğiniz aralıkla otomatik tıklama yapar.",
            "help_multi" to "Çoklu Hedef",
            "help_multi_desc" to "Birden fazla noktayı sırayla tıklar. Yüzen panelden hedef ekleyip düzenleyebilirsiniz.",
            "help_stop" to "Durdurma Koşulu",
            "help_stop_desc" to "Sınırsız, süre veya tıklama sayısına göre otomatik durma seçeneği belirleyin.",
            "help_info" to "Tüm ayarlar ve kontroller yüzen panel üzerinden yapılır. Paneldeki ⚙ butonu ile tıklama hızı, hedef ve durdurma koşullarını ayarlayabilirsiniz.",
            "feedback_title" to "Geri Bildirim",
            "feedback_type" to "Tür",
            "feedback_bug" to "Hata",
            "feedback_idea" to "Öneri",
            "feedback_opinion" to "Görüş",
            "feedback_subject" to "Başlık",
            "feedback_subject_hint" to "Kısa bir başlık girin",
            "feedback_desc" to "Açıklama",
            "feedback_desc_hint" to "Detaylı açıklamanızı yazın",
            "feedback_send" to "Gönder",
            "about_title" to "Uygulama Hakkında",
            "about_version" to "v1.0",
            "about_desc" to "Auto Clicker, belirlediğiniz aralıklarla ekrana otomatik tıklama yapan bir Android uygulamasıdır. Tek hedef veya çoklu hedef desteği ile istediğiniz noktalara otomatik tıklama yapabilirsiniz.",
            "about_links" to "Bağlantılar",
            "lang_title" to "Dil",
            "lang_tr" to "Türkçe",
            "lang_en" to "English",
            "notif_channel" to "Auto Clicker",
            "notif_text" to "Overlay aktif",
            "service_disconnected" to "Servis bağlı değil",
            "service_stopped" to "Durduruldu",
            "service_started" to "Başlatıldı",
            "settings" to "Ayarlar",
            "settings_interval" to "Tıklama Aralığı",
            "settings_stop" to "Durdurma",
            "settings_indefinite" to "Süresiz",
            "settings_time" to "Zaman",
            "settings_clicks" to "Tıklama",
            "settings_position" to "Hedef Pozisyon",
            "settings_drag" to "Hedef işaretini sürükleyin",
            "click" to "tık",
            "click_cancelled" to "tık iptal! Servis sorunu",
            "hint_value" to "değer",
            "target" to "hedef",
            "overlay_active" to "Overlay aktif",
            "email" to "E-posta",
            "source_code" to "Kaynak Kodları",
            "share" to "Uygulamayı Paylaş",
            "share_text" to "Auto Clicker - Otomatik tıklama uygulaması! 🖱️\n🔗 https://github.com/Memati8383/AutoClicker",
        ),
        "en" to mapOf(
            "home" to "Home",
            "help" to "Help",
            "feedback" to "Feedback",
            "about" to "About",
            "exit" to "Exit",
            "app_name" to "Auto Clicker",
            "app_subtitle" to "Auto Click Tool",
            "a11y_title" to "Accessibility Service Required",
            "a11y_text" to "Auto Clicker needs accessibility service enabled:\nSettings > Accessibility > Auto Clicker",
            "a11y_go" to "Open Settings",
            "a11y_later" to "Later",
            "mode_title" to "Mode",
            "mode_single" to "Single Target",
            "mode_multi" to "Multi Target",
            "panel_title" to "Floating Panel",
            "panel_active" to "Active — all settings in the panel",
            "panel_off" to "Off",
            "panel_hint" to "All settings configured via ⚙ button in the overlay",
            "badge_service" to "Service",
            "badge_enable" to "Enable",
            "badge_overlay" to "Overlay",
            "badge_grant" to "Grant",
            "help_title" to "Help",
            "help_setup" to "Setup",
            "help_step1" to "Enable Accessibility Service",
            "help_step1_desc" to "Go to Settings > Accessibility > Auto Clicker and enable the service.",
            "help_step2" to "Grant Overlay Permission",
            "help_step2_desc" to "Allow display over other apps for the floating panel.",
            "help_step3" to "Open Floating Panel",
            "help_step3_desc" to "Toggle the switch on the home screen to activate the floating panel.",
            "help_usage" to "Usage",
            "help_single" to "Single Target",
            "help_single_desc" to "Automatically clicks a single point at the configured interval.",
            "help_multi" to "Multi Target",
            "help_multi_desc" to "Clicks multiple points in sequence. Add and edit targets from the floating panel.",
            "help_stop" to "Stop Condition",
            "help_stop_desc" to "Choose between indefinite, timed, or count-based automatic stopping.",
            "help_info" to "All settings and controls are managed through the floating panel. Use the ⚙ button to adjust click speed, targets, and stop conditions.",
            "feedback_title" to "Feedback",
            "feedback_type" to "Type",
            "feedback_bug" to "Bug",
            "feedback_idea" to "Idea",
            "feedback_opinion" to "Opinion",
            "feedback_subject" to "Subject",
            "feedback_subject_hint" to "Enter a short subject",
            "feedback_desc" to "Description",
            "feedback_desc_hint" to "Write your detailed description",
            "feedback_send" to "Send",
            "about_title" to "About",
            "about_version" to "v1.0",
            "about_desc" to "Auto Clicker is an Android app that performs automated clicks at your specified intervals. Supports single target and multi-target modes.",
            "about_links" to "Links",
            "lang_title" to "Language",
            "lang_tr" to "Türkçe",
            "lang_en" to "English",
            "notif_channel" to "Auto Clicker",
            "notif_text" to "Overlay active",
            "service_disconnected" to "Service not connected",
            "service_stopped" to "Stopped",
            "service_started" to "Started",
            "settings" to "Settings",
            "settings_interval" to "Click Interval",
            "settings_stop" to "Stop",
            "settings_indefinite" to "Indefinite",
            "settings_time" to "Time",
            "settings_clicks" to "Clicks",
            "settings_position" to "Target Position",
            "settings_drag" to "Drag the target marker",
            "click" to "click",
            "click_cancelled" to "click cancelled! Service issue",
            "hint_value" to "value",
            "target" to "target",
            "overlay_active" to "Overlay active",
            "email" to "Email",
            "source_code" to "Source Code",
            "share" to "Share App",
            "share_text" to "Auto Clicker - Automated click tool! 🖱️\n🔗 https://github.com/Memati8383/AutoClicker",
        )
    )

    fun get(key: String): String = all[current]?.get(key) ?: key

    fun setLang(lang: String) {
        if (all.containsKey(lang)) current = lang
    }

    fun toggle() {
        current = if (current == "tr") "en" else "tr"
    }

    fun targets(n: Int) = if (current == "tr") "$n hedef tanımlı — yüzen panelden düzenleyin"
        else "$n targets defined — edit from overlay"

    fun clicks(n: Int) = "$n ${get("click")}"

    fun clickCount(n: Int) = if (current == "tr") "$n tık" else "$n clicks"

    fun targetCount(n: Int) = "$n ${get("target")}"
}
